"""restaurantes URL Configuration"""

from django.conf.urls import include, url
from django.contrib import admin
from registration.backends.simple.views import RegistrationView
from rest_framework_mongoengine import routers
from appRestaurants import serializers

# this is DRF router for REST API viewsets
router = routers.DefaultRouter()

# register REST API endpoints with DRF router
router.register(r'restaurantes', serializers.restaurantesViewSet, r"restaurantes")

# Create a new class that redirects the user to the index page, if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self,request, user):
        return '/restaurantes/home'

urlpatterns = [
  url(r'^restaurantes/', include('appRestaurants.urls')),
  url(r'^admin/', include(admin.site.urls)),
  url(r'^accounts/', include('registration.backends.simple.urls')),
  # REST API root view (generated by DRF router)
  url(r'^api/', include(router.urls, namespace='api'))
]
